apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.44.0
    cacheLevel: 'High'
    incrementalQuerying: true
    incrementalQueryOverlapWindow: 10m
    exemplarTraceIdDestinations:
      # Field with internal link pointing to data source in Grafana.
      # datasourceUid value can be anything, but it should be unique across all defined data source uids.
      - datasourceUid: my_jaeger_uid
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://grafana-tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: Prometheus
      streamingEnabled:
        search: true
