global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log
scrape_configs:
- job_name: 'otel-collector'
  metrics_path: /metrics
  static_configs:
  - targets: [ 'opentelemetry-collector:8889' ]
- job_name: 'tempo'
  static_configs:
  - targets: [ 'grafana-tempo:3200' ]
