global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log
scrape_configs:
- job_name: 'admin'
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: [ '192.168.5.2:8080', '192.168.5.2:8081' ]
